### ISSUE TITLE
Portal Services not available and for replaced by Portal Site

### ISSUE THREAD

**Issue by harikishores** [SAP-samples/hana-shine-xsa#58]
The deployment of the application fails in the Cloud Foundry production account due to the deprecated Portal services.

**Comment by ANUGRAHG** [comment]
Hello Hari,

Can you please share cf logs? We will look into this issue.

Thanks

**Comment by harikishores** [comment]
Hello Anugrahg

Please find the logs

Deploying in org "Aarini Consulting B.V._aarini" and space "AppDevelopment"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment
Detected new MTA version: "1.3.10"
Service "shine-container" exists but doesnt have any bound applications
Service "shine-uaa" exists but doesnt have any bound applications
Processing service "sap-portal-services-client"...
Creating service "sap-portal-services-client" from MTA resource "sap-portal-services-client"...
Unexpected error: Controller operation failed: 403 Forbidden: Error creating service "sap-portal-services-client" from offering "portal-services" and plan "site-content": A service instance for the selected plan cannot be created in this organization. The plan is visible because another organization you belong to has access to it.
Processing service "shine-scheduler"...
Creating service "shine-scheduler" from MTA resource "shine-scheduler"...
Process failed: Unexpected error: Controller operation failed: 403 Forbidden: Error creating service "sap-portal-services-client" from offering "portal-services" and plan "site-content": A service instance for the selected plan cannot be created in this organization. The plan is visible because another organization you belong to has access to it.
Use "cf deploy -i 59831120 -a abort" to abort the process.
Use "cf deploy -i 59831120 -a retry" to retry the process.
Use "cf dmol -i 59831120" to download the logs of the process.

Regards
Harikishore
