### ISSUE TITLE
cannot see SHINE democontent package in HANA

### ISSUE THREAD

**Issue by sivanovWork** [SAP-samples/hana-shine-xsa#59]
We successfully deployed HANA SHINE package(applications are running) on GCP HANA Express but cannot see democontent packages in HANA ?
Please give an idea what to do to see it

**Comment by CHERIANS** [comment]
Hi,
There are two versions of SHINE. Are you talking about SAP HANA DEMO MODEL (SHINE for HANA XS Classic) or SAP HANA DEMO MODEL ADV. (SHINE for XS Advanced). This repository is for SHINE for XS Advanced and it does not have package called as democontent.
