### ISSUE TITLE
SHINE-XSA Installation instructions could be clearer

### ISSUE THREAD

**Issue by rbrainey** [SAP-samples/hana-shine-xsa#62]
Hi,

I'm attempting to follow the instructions as outlined in https://github.com/SAP/hana-shine-xsa/blob/master/SHINE-XSA.md

The "**Importing SHINE from GitHub to SAP Web IDE for SAP HANA**" section abruptly switches from a Web IDE import to executing `xs` commands from the command line.  Currently there's no instructions for downloading a local copy of the repo to get the file referenced in the first `xs` command (that would be trivial, but it _is_ missing), nor any instructions regarding which org and space to target prior to running the `xs` commands.

Would you update the instructions?

Riley

**Comment by CHERIANS** [comment]
Hi Riley,
The detailed instruction of SHINE installation is part of SHINE guide https://help.sap.com/doc/13ff61e61a8f442090e27050dc61f019/2.0.04/en-US/SAP_HANA_Interactive_Education_SHINE_for_SAP_HANA_XS_Advanced_en_HANA2.0SPS04.pdf (Please refer to chapter 3.1)
The Github documentation is just a subset of it.
Best Regards
Stephen
