### ISSUE TITLE
The MTA Archive Builder is deprecated. The guide should be updated to refer to the new tool

### ISSUE THREAD

**Issue by katunin-ng** [SAP-samples/hana-shine-xsa#63]
HI,

The old tool used for building MTA archives, Multitarget application archive builder, is deprecated. The new tool is already available. For more info, please read the blog: https://blogs.sap.com/2019/11/19/enjoy-our-new-tool-for-building-mta-archives/.

This guide should be updated with info about the new tool.
Regards
Natalia

**Comment by syy6** [comment]
Also nodejs v6 runtime is not avalible in CP.

**Comment by ANUGRAHG** [comment]
done
