### ISSUE TITLE
Can't clone repository https://github.com/SAP/hana-shine-xsa

### ISSUE THREAD

**Issue by jjairoph** [SAP-samples/hana-shine-xsa#67]
When I try to clone the repository in SAP Web IDE for SAP HANA , I get the message:
![2020-05-09 05_22_47-SAP Web IDE for SAP HANA](https://user-images.githubusercontent.com/3811263/81471231-56d30700-91b5-11ea-8076-eb4e7327f1e4.png)

**Comment by CHERIANS** [comment]
Hi,
Can you check if you are behind a proxy. As there seems to be a connectivity issue from SAP Web IDE to github.
Best Regards
Stephen

**Comment by CHERIANS** [comment]
Please feel free to re open the issue if you still face the issue.
Best regards
Stephen
