### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by Pizent** [SAP-samples/hana-shine-xsa#89]
After we finish shine deployment on the last step of the instruction we encounter error as shown in the screenshots.

![image](https://user-images.githubusercontent.com/123958242/215490828-e3dc2c2b-ff00-4ee0-bf08-994103a10526.png)

When clicked on "Check Prerequisites"  we get 

![image](https://user-images.githubusercontent.com/123958242/215490458-e36568e3-9d11-45a5-9937-f9cbd01bba5e.png)

![image](https://user-images.githubusercontent.com/123958242/215490481-b33b2c54-6ebc-453a-9e55-282231e9557c.png)

We checked and the user we used for deployment already has needed role
![image](https://user-images.githubusercontent.com/123958242/215491232-00f21448-500a-4c61-9ce8-11c7b58fea01.png)

Any suggestions what to do next ?

**Comment by LalithManokar** [comment]
HI @Pizent ,

Are you facing the issue still?

Regards,
Lalith. S

**Comment by LalithManokar** [comment]
HI @Pizent ,

issue is because of xs-security.json file is not deployed properly.
try to create the xsuaa instance manually and bound to the applications and restart.

this will fix the issue

Regards,
Lalith. S

**Comment by LalithManokar** [comment]
closing issue no reply
