### ISSUE TITLE
SHINE for HANA Express 2.0 SPS07

### ISSUE THREAD

**Issue by jaime-miranda** [SAP-samples/hana-shine-xsa#93]
Hi guys,

I just installed HANA Express 2.0 SPS07 on my OpenSuse VM. I'd like to load some data on my new system but the DownloadManager isn't showing the SHINE package anymore. 

According to all tutorials that I found so far SHINE should be installed unpacking the tar files provided by the DownloadManager and running the installer program. 
How can I install the SHINE demos using the files published in Github? I don't see any installer there.

![image](https://github.com/SAP-samples/hana-shine-xsa/assets/148969454/cba51679-cbf8-4570-aed6-00568a5b97b7)

Best regards,

Jaime

**Comment by LalithManokar** [comment]
Hi We have provided the ways to install the SHINE demo content , we don't provide any package for shine in "DownloadManager"
