### ISSUE TITLE
npm ERR! notarget No matching version found for sax@1.1.4.

### ISSUE THREAD

**Issue by pradeep87gupta** [SAP-samples/hana-shine-xsa#96]
Hi,
while running  or trying to build the core-node module we are getting the following error message. 
(DIBuild) npm ERR! code ETARGETnpm 
ERR! notarget No matching version found for sax@1.1.4.npm 
ERR! notarget In most cases you or one of your dependencies are requesting npm 
ERR! notarget a package version that doesn't exist.

We were not able to locate where sax package is being referred in the core-node module. The error still persists even if we include it in the package.json file. 

Rest all modules are getting built and running fine.

We tried using HANA 2.0 SPS05 and SPS07 versions.

**Comment by LalithManokar** [comment]
@pradeep87gupta 

Please Check the Npm registry once, issue occur because of npm registry is not been set properly. https://www.npmjs.com/package/sax/v/1.1.4

Regards,
Lalith. S

**Comment by pradeep87gupta** [comment]
Hi @LalithManokar, 
thanks for coming back on this. 
We checked our system and our admin team says that this npm package exists in the registry. 
We have also setup the UPSTREAMLINK and SAPUPSTREAM_LINK as below
UPSTREAM_LINK: "http://registry.npmjs.org/"
SAPUPSTREAM_LINK: "https://registry.npmjs.org"

All other modules like core-xsjs and user-xsjs are getting built and running fine. 

Only in the core-node project its prompting this error even though we if we include it in the package.json file as a dependency 
    "sax" : "1.2.4"

Could please let us know where exactly should we be checking this npm registry whether it has been setup properly or not?

![sax npm in HANA XSA](https://github.com/SAP-samples/hana-shine-xsa/assets/8491223/50eb4514-5f1a-406c-988b-34ff6554fcf5)

**Comment by LalithManokar** [comment]
Please Check the documentation 

https://help.sap.com/docs/SAP_HANA_PLATFORM/4505d0bdaf4948449b7f7379d24d0f0d/726e5d41462c4eb29eaa6cc83ff41e84.html?q=UPSTREAM_LINK

Regards,
Lalith. S

**Comment by pradeep87gupta** [comment]
Hi @LalithManokar,

Thanks a lot. Your solution worked for us and now we dont have the npm error anymore.

I have run into other issue now. Could you also please check that. Thank you!
https://github.com/SAP-samples/hana-shine-xsa/issues/97
